### PR TITLE
Update and add new Agents for v09 of the FREME API

### PR DESCRIPTION
**Pull request by dsander**

### CODE REVIEW

**Comment by dsander** [comment]
@davidwabnitz To test this add the gem to your `ADDITIONAL_GEMS`:  

```
huginn_freme_enrichment_agents(github: kreuzwerker/DKT.huginn_freme_enrichment_agents, branch: agent-updates)
```

Please use the `huginnbuilder/huginn:pr-1690` docker image, it contains changes required for the file upload of the `NifConverterAgent` that are not merged into Huginn yet.

**Review by davidwabnitz — CHANGES_REQUESTED** [review]
Following issues currently exist for 

all Agents - think about standardizing informat, outformat and bodyformat option labels (currently a mix of styles is in use, e.g. 'json-ld' vs. 'application/ld+json'). Maybe stick to content-type/ accept-header style labels, even though they're more difficult to read/understand for users?

existing Agents (not when creating new instances):
- FremeFilterAgent
  *\* Select-Fields 'Body format', 'Outformat' and 'Name' have issue populating with data.
  *\* Field-label 'Name' for name of filter select should be changed to 'Filter name'
- FremePipelineAgent - Select-Fields 'Body format' and 'Template' have issue populating with data.
- FremeNifConverterAgent  - Select-Fields 'Body format' and 'Outformat' have issue populating with data.
  FremeLinkAgent  - Select-Fields 'Body format',  'Outformat', and 'Templateid' have issue populating with data.
  FremeNerAgent  - Select-Fields 'Body format',  'Outformat', 'Dataset', 'Language', 'Mode', 'Linkingmethod' and 'Filter' have issue populating with data.

**Comment by davidwabnitz** [comment]
@dsander maybe the above issue with populating the selects is somehow related to the following error (bcs if I propagete_immediately is not set, the select widget populates as it should):

```
7:49:56 web.1  | Completed 500 Internal Server Error in 4ms (ActiveRecord: 0.4ms)
17:49:56 web.1  |
17:49:56 web.1  | ActionController::UnpermittedParameters - found unpermitted parameter: propagate_immediately:
17:49:56 web.1  |   actionpack (4.2.7.1) lib/action_controller/metal/strong_parameters.rb:497:in `unpermitted_parameters!'
17:49:56 web.1  |   actionpack (4.2.7.1) lib/action_controller/metal/strong_parameters.rb:339:in `permit'
17:49:56 web.1  |   app/controllers/application_controller.rb:68:in `agent_params'
17:49:56 web.1  |   app/controllers/agents_controller.rb:223:in `build_agent'
17:49:56 web.1  |   app/controllers/agents_controller.rb:206:in `complete'
17:49:56 web.1  |   actionpack (4.2.7.1) lib/action_controller/metal/implicit_render.rb:4:in `send_action'
17:49:56 web.1  |   actionpack (4.2.7.1) lib/abstract_controller/base.rb:198:in `process_action'
17:49:56 web.1  |   actionpack (4.2.7.1) lib/action_controller/metal/rendering.rb:10:in `process_action'
17:49:56 web.1  |   actionpack (4.2.7.1) lib/abstract_controller/callbacks.rb:20:in `block in process_action'
17:49:56 web.1  |   activesupport (4.2.7.1) lib/active_support/callbacks.rb:117:in `call'
17:49:56 web.1  |   activesupport (4.2.7.1) lib/active_support/callbacks.rb:555:in `block (2 levels) in compile'
17:49:56 web.1  |   activesupport (4.2.7.1) lib/active_support/callbacks.rb:505:in `call'
17:49:56 web.1  |   activesupport (4.2.7.1) lib/active_support/callbacks.rb:92:in `__run_callbacks__'
17:49:56 web.1  |   activesupport (4.2.7.1) lib/active_support/callbacks.rb:778:in `_run_process_action_callbacks'
17:49:56 web.1  |   activesupport (4.2.7.1) lib/active_support/callbacks.rb:81:in `run_callbacks'
17:49:56 web.1  |   actionpack (4.2.7.1) lib/abstract_controller/callbacks.rb:19:in `process_action'
17:49:56 web.1  |   actionpack (4.2.7.1) lib/action_controller/metal/rescue.rb:29:in `process_action'
17:49:56 web.1  |   actionpack (4.2.7.1) lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
17:49:56 web.1  |   activesupport (4.2.7.1) lib/active_support/notifications.rb:164:in `block in instrument'
17:49:56 web.1  |   activesupport (4.2.7.1) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
17:49:56 web.1  |   activesupport (4.2.7.1) lib/active_support/notifications.rb:164:in `instrument'
17:49:56 web.1  |   actionpack (4.2.7.1) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
17:49:56 web.1  |   actionpack (4.2.7.1) lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
17:49:56 web.1  |   activerecord (4.2.7.1) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
17:49:56 web.1  |   actionpack (4.2.7.1) lib/abstract_controller/base.rb:137:in `process'
17:49:56 web.1  |   actionview (4.2.7.1) lib/action_view/rendering.rb:30:in `process'
17:49:56 web.1  |   actionpack (4.2.7.1) lib/action_controller/metal.rb:196:in `dispatch'
17:49:56 web.1  |   actionpack (4.2.7.1) lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
17:49:56 web.1  |   actionpack (4.2.7.1) lib/action_controller/metal.rb:237:in `block in action'
17:49:56 web.1  |   actionpack (4.2.7.1) lib/action_dispatch/routing/route_set.rb:74:in `dispatch'
17:49:56 web.1  |   actionpack (4.2.7.1) lib/action_dispatch/routing/route_set.rb:43:in `serve'
17:49:56 web.1  |   actionpack (4.2.7.1) lib/action_dispatch/journey/router.rb:43:in `block in serve'
17:49:56 web.1  |   actionpack (4.2.7.1) lib/action_dispatch/journey/router.rb:30:in `serve'
17:49:56 web.1  |   actionpack (4.2.7.1) lib/action_dispatch/routing/route_set.rb:817:in `call'
17:49:56 web.1  |   omniauth (1.2.2) lib/omniauth/strategy.rb:186:in `call!'
17:49:56 web.1  |   omniauth (1.2.2) lib/omniauth/strategy.rb:164:in `call'
17:49:56 web.1  |   omniauth (1.2.2) lib/omniauth/strategy.rb:186:in `call!'
17:49:56 web.1  |   omniauth (1.2.2) lib/omniauth/strategy.rb:164:in `call'
17:49:56 web.1  |   omniauth (1.2.2) lib/omniauth/strategy.rb:186:in `call!'
17:49:56 web.1  |   omniauth (1.2.2) lib/omniauth/strategy.rb:164:in `call'
17:49:56 web.1  |   warden (1.2.4) lib/warden/manager.rb:35:in `block in call'
17:49:56 web.1  |   warden (1.2.4) lib/warden/manager.rb:34:in `call'
17:49:56 web.1  |   rack (1.6.4) lib/rack/etag.rb:24:in `call'
17:49:56 web.1  |   rack (1.6.4) lib/rack/conditionalget.rb:38:in `call'
17:49:56 web.1  |   rack (1.6.4) lib/rack/head.rb:13:in `call'
17:49:56 web.1  |   actionpack (4.2.7.1) lib/action_dispatch/middleware/params_parser.rb:27:in `call'
17:49:56 web.1  |   actionpack (4.2.7.1) lib/action_dispatch/middleware/flash.rb:260:in `call'
17:49:56 web.1  |   rack (1.6.4) lib/rack/session/abstract/id.rb:225:in `context'
17:49:56 web.1  |   rack (1.6.4) lib/rack/session/abstract/id.rb:220:in `call'
17:49:56 web.1  |   actionpack (4.2.7.1) lib/action_dispatch/middleware/cookies.rb:560:in `call'
17:49:56 web.1  |   activerecord (4.2.7.1) lib/active_record/query_cache.rb:36:in `call'
17:49:56 web.1  |   activerecord (4.2.7.1) lib/active_record/connection_adapters/abstract/connection_pool.rb:653:in `call'
17:49:56 web.1  |   activerecord (4.2.7.1) lib/active_record/migration.rb:377:in `call'
17:49:56 web.1  |   actionpack (4.2.7.1) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
17:49:56 web.1  |   activesupport (4.2.7.1) lib/active_support/callbacks.rb:88:in `__run_callbacks__'
17:49:56 web.1  |   activesupport (4.2.7.1) lib/active_support/callbacks.rb:778:in `_run_call_callbacks'
17:49:56 web.1  |   activesupport (4.2.7.1) lib/active_support/callbacks.rb:81:in `run_callbacks'
17:49:56 web.1  |   actionpack (4.2.7.1) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
17:49:56 web.1  |   actionpack (4.2.7.1) lib/action_dispatch/middleware/reloader.rb:73:in `call'
17:49:56 web.1  |   actionpack (4.2.7.1) lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
17:49:56 web.1  |   better_errors (1.1.0) lib/better_errors/middleware.rb:84:in `protected_app_call'
17:49:56 web.1  |   better_errors (1.1.0) lib/better_errors/middleware.rb:79:in `better_errors_call'
17:49:56 web.1  |   better_errors (1.1.0) lib/better_errors/middleware.rb:56:in `call'
17:49:56 web.1  |   actionpack (4.2.7.1) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
17:49:56 web.1  |   actionpack (4.2.7.1) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
17:49:56 web.1  |   railties (4.2.7.1) lib/rails/rack/logger.rb:38:in `call_app'
17:49:56 web.1  |   railties (4.2.7.1) lib/rails/rack/logger.rb:20:in `block in call'
17:49:56 web.1  |   activesupport (4.2.7.1) lib/active_support/tagged_logging.rb:68:in `block in tagged'
17:49:56 web.1  |   activesupport (4.2.7.1) lib/active_support/tagged_logging.rb:26:in `tagged'
17:49:56 web.1  |   activesupport (4.2.7.1) lib/active_support/tagged_logging.rb:68:in `tagged'
17:49:56 web.1  |   railties (4.2.7.1) lib/rails/rack/logger.rb:20:in `call'
17:49:56 web.1  |   config/initializers/silence_worker_status_logger.rb:5:in `call_with_silence_worker_status'
17:49:56 web.1  |   quiet_assets (1.1.0) lib/quiet_assets.rb:27:in `call_with_quiet_assets'
17:49:56 web.1  |   actionpack (4.2.7.1) lib/action_dispatch/middleware/request_id.rb:21:in `call'
17:49:56 web.1  |   rack (1.6.4) lib/rack/methodoverride.rb:22:in `call'
17:49:56 web.1  |   rack (1.6.4) lib/rack/runtime.rb:18:in `call'
17:49:56 web.1  |   activesupport (4.2.7.1) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
17:49:56 web.1  |   rack (1.6.4) lib/rack/lock.rb:17:in `call'
17:49:56 web.1  |   rack-livereload (0.3.16) lib/rack/livereload.rb:23:in `_call'
17:49:56 web.1  |   rack-livereload (0.3.16) lib/rack/livereload.rb:14:in `call'
17:49:56 web.1  |   actionpack (4.2.7.1) lib/action_dispatch/middleware/static.rb:120:in `call'
17:49:56 web.1  |   rack (1.6.4) lib/rack/sendfile.rb:113:in `call'
17:49:56 web.1  |   railties (4.2.7.1) lib/rails/engine.rb:518:in `call'
17:49:56 web.1  |   railties (4.2.7.1) lib/rails/application.rb:165:in `call'
17:49:56 web.1  |   rack (1.6.4) lib/rack/lock.rb:17:in `call'
17:49:56 web.1  |   rack (1.6.4) lib/rack/content_length.rb:15:in `call'
17:49:56 web.1  |   rack (1.6.4) lib/rack/handler/webrick.rb:88:in `service'
17:49:56 web.1  |   /Users/dw/.rbenv/versions/2.1.3/lib/ruby/2.1.0/webrick/httpserver.rb:138:in `service'
17:49:56 web.1  |   /Users/dw/.rbenv/versions/2.1.3/lib/ruby/2.1.0/webrick/httpserver.rb:94:in `run'
17:49:56 web.1  |   /Users/dw/.rbenv/versions/2.1.3/lib/ruby/2.1.0/webrick/server.rb:295:in `block in start_thread'
17:49:56 web.1  |
```

**Comment by dsander** [comment]
@davidwabnitz The completion bug is fixed in https://github.com/cantino/huginn/pull/1698

The `outformat` and `body_format` values have been copied over from the FREME documentation when the Agents were written. I will go through them again tomorrow and adjust our values to theirs (which all seem to be unified now).

**Comment by dsander** [comment]
@davidwabnitz The `outformat` values are not up to date with the official documentation.

**Review by davidwabnitz — APPROVED** [review]

**Comment by dsander** [comment]
👍 Thanks

**Pull request merged**
